#throw exception and call without try block
def throw_exception():
    raise ValueError("ERROR")
throw_exception()